name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: What were you trying to do, what did you expect, and what was the actual result?
      placeholder: Describe the issue here
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
