name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Please provide a clear and concise description of the bug here. Include screenshots if needed.
      placeholder: Describe the issue here
      value: |
        ## What were you trying to do?
        
        ## Expected Behavior
        
        ## Actual Result
        
        ## Steps to Reproduce
        1.
        2.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
